// This file is auto-generated by bundle_qml.py. Do not edit it directly.

import QtQuick 2.12
import Vedder.vesc.utility 1.0
import Vedder.vesc.commands 1.0
import Vedder.vesc.configparams 1.0
import QtQuick.Controls 2.12
import QtQuick.Layouts 1.3

/*
    Production entry point loaded by VESC Tool.
*/


Item {
    component CustomTextRef: Text {
        required property var mUtility

        color: mUtility.getAppHexColor("black")
    }

    component GaugeRef: Rectangle {
        id: gauge



        required property real inputValue
        required property var mUtility

        property real minValue: 0.0
        property real maxValue: 100.0
        property real safetyMargin: 50.0
        property real borderWidth: 2.0
        property real labelPadding: 4.0
        property bool inverted: false
        property string valueUnit: ""
        property string rangeUnit: valueUnit
        property string label: ""
        property int valueDecimals: 1
        property int rangeDecimals: 1

        readonly property real value:
            Math.max(minValue, Math.min(maxValue, inputValue))
        readonly property real normalizedPercentage:
            maxValue > minValue
                ? ((value - minValue) / (maxValue - minValue)) * 100.0
                : 0.0
        readonly property real percentage:
            inverted ? 100.0 - normalizedPercentage : normalizedPercentage
        readonly property real topValue: inverted ? minValue : maxValue
        readonly property real bottomValue: inverted ? maxValue : minValue

        color: mUtility.getAppHexColor("darkBackground")

        function gaugeColor(percentageValue, margin) {
            if (percentageValue <= margin) {
                return Qt.rgba(0.0, 0.45, 0.0, 1.0)
            }

            var denominator = 100.0 - margin
            var transition = denominator > 0.0
                    ? (percentageValue - margin) / denominator
                    : 1.0
            transition = Math.max(0.0, Math.min(1.0, transition))

            if (transition <= 0.5) {
                var greenToYellow = transition / 0.5
                return Qt.rgba(greenToYellow * 0.5, 0.45, 0.0, 1.0)
            }

            var yellowToRed = (transition - 0.5) / 0.5
            return Qt.rgba(0.5, 0.45 * (1.0 - yellowToRed), 0.0, 1.0)
        }

        Rectangle {
            anchors.left: parent.left
            anchors.top: parent.top
            anchors.bottom: parent.bottom
            width: gauge.borderWidth
            color: mUtility.getAppHexColor("lightText")
        }

        Rectangle {
            anchors.right: parent.right
            anchors.top: parent.top
            anchors.bottom: parent.bottom
            width: gauge.borderWidth
            color: mUtility.getAppHexColor("lightText")
        }

        Rectangle {
            anchors.left: parent.left
            anchors.top: parent.top
            anchors.right: topValueLabelBackground.left
            height: gauge.borderWidth
            color: mUtility.getAppHexColor("lightText")
        }

        Rectangle {
            anchors.left: topValueLabelBackground.right
            anchors.top: parent.top
            anchors.right: parent.right
            height: gauge.borderWidth
            color: mUtility.getAppHexColor("lightText")
        }

        Rectangle {
            anchors.left: parent.left
            anchors.bottom: parent.bottom
            anchors.right: bottomValueLabelBackground.left
            height: gauge.borderWidth
            color: mUtility.getAppHexColor("lightText")
        }

        Rectangle {
            anchors.left: bottomValueLabelBackground.right
            anchors.bottom: parent.bottom
            anchors.right: parent.right
            height: gauge.borderWidth
            color: mUtility.getAppHexColor("lightText")
        }

        Rectangle {
            z: 0
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.bottom: parent.bottom
            height: parent.height * gauge.percentage / 100.0
            color: gauge.gaugeColor(gauge.percentage, gauge.safetyMargin)

            Behavior on height {
                NumberAnimation {
                    duration: 100
                    easing.type: Easing.OutQuad
                }
            }
        }

        Rectangle {
            id: topValueLabelBackground
            z: 1
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.top: parent.top
            anchors.topMargin: -gauge.borderWidth
            width: topValueLabel.width + 4
            height: topValueLabel.height + gauge.labelPadding * 2
            color: "transparent"
        }

        CustomTextRef {
            id: topValueLabel
            mUtility: gauge.mUtility
            z: 2
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.verticalCenter: parent.top
            anchors.verticalCenterOffset: gauge.borderWidth / 2
            text: gauge.topValue.toFixed(gauge.rangeDecimals) + gauge.rangeUnit
            font.pixelSize: 16
            font.weight: Font.Normal
        }

        Rectangle {
            id: bottomValueLabelBackground
            z: 1
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.bottom: parent.bottom
            anchors.bottomMargin: -gauge.borderWidth
            width: bottomValueLabel.width + 4
            height: bottomValueLabel.height + gauge.labelPadding * 2
            color: "transparent"
        }

        CustomTextRef {
            id: bottomValueLabel
            mUtility: gauge.mUtility
            z: 2
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.verticalCenter: parent.bottom
            anchors.verticalCenterOffset: -gauge.borderWidth / 2
            text: gauge.bottomValue.toFixed(gauge.rangeDecimals) + gauge.rangeUnit
            font.pixelSize: 16
            font.weight: Font.Normal
        }

        Rectangle {
            anchors.left: parent.left
            anchors.right: parent.right
            anchors.bottom: parent.bottom
            anchors.bottomMargin: parent.height * gauge.safetyMargin / 100.0
            height: 2
            color: mUtility.getAppHexColor("lightText")
            opacity: 0.7
        }

        CustomTextRef {
            id: valueLabel
            mUtility: gauge.mUtility
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.top: parent.top
            anchors.topMargin: 20
            text: gauge.value.toFixed(gauge.valueDecimals) + gauge.valueUnit
            font.pixelSize: 30
            font.weight: Font.Black
        }

        CustomTextRef {
            mUtility: gauge.mUtility
            anchors.horizontalCenter: parent.horizontalCenter
            anchors.top: valueLabel.bottom
            anchors.topMargin: 2
            text: gauge.label
            verticalAlignment: Text.AlignTop
            horizontalAlignment: Text.AlignHCenter
            font.pixelSize: 14
            font.weight: Font.Black
        }
    }

    /*
        Copyright 2022 Benjamin Vedder	benjamin@vedder.se

        This file is part of VESC Tool.

        VESC Tool is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        VESC Tool is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program.  If not, see <http://www.gnu.org/licenses/>.
        */

    // This example shows how to read and write settings using the custom
    // config. It is also possible to send and receive custom data using
    // send_app_data and set_app_data_handler on the euc-side and Commands
    // onCustomAppDataReceived and mCommands.sendCustomAppData in qml.
    component BalanceUiRef: Item {
        id: mainItem
        anchors.fill: parent
        anchors.margins: 5

        required property var mCommands
        required property var mMcConf
        required property var mCustomConf
        required property var mUtility
        required property string appVersion




        readonly property int balanceCommandGetRealtimeData: 0x01
        readonly property int balanceCommandTriggerKillspin: 0x02

        // Gauge values
        property real dutyCycle: 0.0
        property real motorCurrent: 0.0
        property real batteryVoltage: 84.0
        property real speedKmh: 0.0
        property real maxMotorCurrent: mMcConf ? mMcConf.getParamDouble("l_current_max") : 100.0
        property real tempFet: 0.0
        property real tempMotor: 0.0

        Component.onCompleted: {
            // Request VESC values periodically
            requestVescValues()
        }

        function requestVescValues() {
            if (mCommands) {
                mCommands.getValues()
            }
        }

        Timer {
            running: true
            repeat: true
            interval: 100

            onTriggered: {
                var buffer = new ArrayBuffer(1)
                var dv = new DataView(buffer)
                dv.setUint8(0, balanceCommandGetRealtimeData)
                mCommands.sendCustomAppData(buffer)
            }
        }

        // Request VESC values periodically for gauges
        Timer {
            running: true
            repeat: true
            interval: 200

            onTriggered: {
                requestVescValues()
            }
        }

        Connections {
            target: mCommands

            // Get VESC realtime values (duty cycle, temperature)
            onValuesReceived: {
                if (values) {
                    dutyCycle = Math.abs(values.duty_now) * 100.0
                    // Note: batteryVoltage and speedKmh are now updated from ui_data
                    // in onCustomAppDataReceived
                    if (typeof values.temp_mos !== "undefined") {
                        tempFet = values.temp_mos
                    }
                    if (typeof values.temp_motor !== "undefined") {
                        tempMotor = values.temp_motor
                    }
                }
            }

            // This function will be called when VESC_IF->send_app_data is used. To
            // send data back mCommands.sendCustomAppData can be used. That data
            // will be received in the function registered with VESC_IF->set_app_data_handler
            onCustomAppDataReceived: {
                // Ints and floats can be extracted like this from the data
                var dv = new DataView(data, 0)
                var ind = 0
                var pid_value = dv.getFloat32(ind); ind += 4;
                var pitch = dv.getFloat32(ind); ind += 4;
                var roll = dv.getFloat32(ind); ind += 4;
                var time_diff = dv.getFloat32(ind); ind += 4;
                var motor_current = dv.getFloat32(ind); ind += 4;
                var state = dv.getInt16(ind); ind += 2;
                var setpoint = dv.getFloat32(ind); ind += 4;
                var motor_load = dv.getFloat32(ind); ind += 4;
                var motor_accel_load = dv.getFloat32(ind); ind += 4;
                var killSwitchTriggered = dv.getInt16(ind); ind += 2;
                var tiltback_type = dv.getInt16(ind); ind += 2;
                // UI data values
                var rpm = dv.getFloat32(ind); ind += 4;
                var speed_kmh = dv.getFloat32(ind); ind += 4;
                var voltage = dv.getFloat32(ind); ind += 4;
                var voltage_min = dv.getFloat32(ind); ind += 4;
                var voltage_max = dv.getFloat32(ind); ind += 4;

                // Update motor current for gauge
                motorCurrent = Math.abs(motor_current)

                // Update speed from ui_data
                speedKmh = speed_kmh

                // Update voltage gauge with ui_data values
                if (voltage_min > 0 && voltage_max > 0) {
                    voltageGauge.minValue = voltage_min
                    voltageGauge.maxValue = voltage_max
                }
                batteryVoltage = voltage

                var stateString
                if (state == 0) {
                    stateString = "STARTUP"
                } else if (state == 1) {
                    stateString = "CENTERING"
                } else if (state == 2) {
                    stateString = "RUNNING"
                } else if (state == 3) {
                    stateString = "FAULT_ANGLE_PITCH"
                } else if (state == 4) {
                    stateString = "FAULT_ANGLE_ROLL"
                } else if (state == 5) {
                    stateString = "FAULT_DUTY"
                } else if (state == 6) {
                    stateString = "READY"
                } else if (state == 7) {
                    stateString = "KILLSPIN"
                } else {
                    stateString = "UNKNOWN"
                }

                var killSwitchTriggeredString
                if(killSwitchTriggered == 0){
                    killSwitchTriggeredString = "No"
                }else{
                    killSwitchTriggeredString = "Yes"
                }

                var tiltbackString
                if (tiltback_type == 0) {
                    tiltbackString = "None"
                } else if (tiltback_type == 1) {
                    tiltbackString = "Duty"
                } else if (tiltback_type == 2) {
                    tiltbackString = "High Voltage"
                } else if (tiltback_type == 3) {
                    tiltbackString = "Low Voltage"
                } else if (tiltback_type == 4) {
                    tiltbackString = "Backing Off"
                } else {
                    tiltbackString = "Unknown"
                }

                valText1.text =
                    "rpm: " + rpm.toFixed(1) + "\n" +
                    "speed: " + speed_kmh.toFixed(1) + "kmh\n" +
                    "setpt: " + setpoint.toFixed(2) + "°\n" +
                    "pitch  : " + pitch.toFixed(2) + "°\n" +
                    "setp-pitch :" + (setpoint-pitch).toFixed(2) + "\n" +
                    "roll   : " + roll.toFixed(2) + "°\n" +
                    "Motor Load : " + motor_load.toFixed(5) + "\n" +
                    "Motor Accel Load : " + motor_accel_load.toFixed(5) + "\n" +
                    "state  : " + stateString + "\n" +
                    "tiltback: " + tiltbackString + "\n" +
                    "kill spin triggered: " + killSwitchTriggeredString;
            }
        }

        ColumnLayout {
            id: mainColumn
            anchors.fill: parent

            StackLayout {
                id: stackLayout
                Layout.fillWidth: true
                Layout.fillHeight: true
                currentIndex: tabBar.currentIndex

                // Tab 1 - EUC RT data with gauges
                ColumnLayout {
                    id: rtDataColumn
                    anchors.fill: parent
                    spacing: 10

                    // Speed and temperature header above gauges
                    RowLayout {
                        id: headerRow
                        Layout.fillWidth: true
                        Layout.preferredHeight: 60
                        Layout.topMargin: 20
                        Layout.bottomMargin: 10
                        spacing: 10

                        // FET temperature
                        ColumnLayout {
                            Layout.fillWidth: true

                            CustomTextRef {
                                id: fetValueText
                                mUtility: mainItem.mUtility
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                font.pixelSize: 28
                                font.weight: Font.Black
                                text: tempFet.toFixed(1)
                            }

                            CustomTextRef {
                                mUtility: mainItem.mUtility
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                font.pixelSize: 16
                                font.weight: Font.Black
                                text: "fet °C"
                            }
                        }

                        // Speed
                        ColumnLayout {
                            Layout.fillWidth: true

                            CustomTextRef {
                                id: speedValueText
                                mUtility: mainItem.mUtility
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                font.pixelSize: 35
                                font.weight: Font.Black
                                text: speedKmh.toFixed(1)
                            }

                            CustomTextRef {
                                mUtility: mainItem.mUtility
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                font.pixelSize: 16
                                font.weight: Font.Black
                                text: "kmh"
                            }
                        }

                        // Motor temperature
                        ColumnLayout {
                            Layout.fillWidth: true

                            CustomTextRef {
                                id: motValueText
                                mUtility: mainItem.mUtility
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                font.pixelSize: 28
                                font.weight: Font.Black
                                text: tempMotor.toFixed(1)
                            }

                            CustomTextRef {
                                mUtility: mainItem.mUtility
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                font.pixelSize: 16
                                font.weight: Font.Black
                                text: "mot °C"
                            }
                        }
                    }

                    // Gauges row
                    RowLayout {
                        Layout.fillWidth: true
                        Layout.preferredHeight: 200
                        spacing: 20

                        GaugeRef {
                            Layout.fillWidth: true
                            Layout.fillHeight: true
                            inputValue: dutyCycle
                            minValue: 0.0
                            maxValue: 100.0
                            rangeUnit: "%"
                            label: "Duty%"
                            rangeDecimals: 0
                            mUtility: mainItem.mUtility
                        }

                        GaugeRef {
                            Layout.fillWidth: true
                            Layout.fillHeight: true
                            inputValue: motorCurrent
                            minValue: 0.0
                            maxValue: maxMotorCurrent
                            valueUnit: "A"
                            label: "Phase\nCurrent"
                            mUtility: mainItem.mUtility
                        }

                        GaugeRef {
                            id: voltageGauge
                            Layout.fillWidth: true
                            Layout.fillHeight: true
                            inputValue: batteryVoltage
                            minValue: 60.0
                            maxValue: 84.0
                            inverted: true
                            valueUnit: "V"
                            label: "Battery\nVoltage"
                            mUtility: mainItem.mUtility
                        }
                    }
                    // Spacer for future features
                    Item {
                        Layout.fillWidth: true
                        Layout.fillHeight: true
                    }
                }

                // Tab 2 - Original content
                ColumnLayout {
                    id: gaugeColumn
                    anchors.fill: parent

                    ScrollView {
                        Layout.fillWidth: true
                        Layout.fillHeight: true
                        clip: true

                        ColumnLayout {
                            Text {
                                id: header
                                color: mUtility.getAppHexColor("lightText")
                                font.family: "DejaVu Sans Mono"
                                Layout.margins: 0
                                Layout.leftMargin: 0
                                Layout.fillWidth: true
                                text: qsTr("Balance App v%1\nRT Data")
                                      .arg(appVersion)
                                font.underline: true
                                font.weight: Font.Black
                            }

                            Text {
                                id: valText1
                                color: mUtility.getAppHexColor("lightText")
                                font.family: "DejaVu Sans Mono"
                                Layout.margins: 0
                                Layout.leftMargin: 5
                                Layout.preferredWidth: parent.width/3
                                text: "App not connected"
                            }

                            Text {
                                Layout.fillWidth: true
                                color: mUtility.getAppHexColor("lightText")
                                horizontalAlignment: Text.AlignHCenter
                                font.pointSize: 20
                                text: "Controls"
                            }

                            Button {
                                Layout.fillWidth: true
                                text: "Kill Switch"

                                onClicked: {
                                    var buffer = new ArrayBuffer(1)
                                    var dv = new DataView(buffer)
                                    dv.setUint8(0, balanceCommandTriggerKillspin)
                                    mCommands.sendCustomAppData(buffer)
                                }
                            }

                            Text {
                                Layout.fillWidth: true
                                color: mUtility.getAppHexColor("lightText")
                                horizontalAlignment: Text.AlignHCenter
                                font.pointSize: 20
                                text: "Data Logging"
                            }

                            CheckBox {
                                id: appendGnss
                                Layout.fillWidth: true
                                text: "Append GNSS"
                                checked: true
                            }

                            RowLayout {
                                Layout.fillWidth: true

                                Text {
                                    color: mUtility.getAppHexColor("lightText")
                                    text: "Log Rate:"
                                    Layout.preferredWidth: 100
                                }

                                ComboBox {
                                    id: logRate
                                    Layout.fillWidth: true
                                    model: [20, 50, 100, 200, 500, 1000]
                                    currentIndex: 5 // Default to 1000
                                }
                            }

                            Button {
                                Layout.fillWidth: true
                                text: "Start Log"

                                onClicked: {
                                    var cmd = "(start-log " + appendGnss.checked + " " + logRate.model[logRate.currentIndex] + ")"
                                    sendCode(cmd)
                                }
                            }

                            Button {
                                Layout.fillWidth: true
                                text: "Stop Log"

                                onClicked: {
                                    var cmd = "(stop-log)"
                                    sendCode(cmd)
                                }
                            }
                        }
                    }
                }
            }

            TabBar {
                id: tabBar
                Layout.fillWidth: true

                TabButton {
                    text: "EUC RT data"
                }

                TabButton {
                    text: "Debug stuff"
                }
            }
        }

        function sendCode(str) {
            mCommands.lispSendReplCmd(str)
        }
    }

    anchors.fill: parent



    BalanceUiRef {
        anchors.fill: parent
        appVersion: "{{VERSION}}"
        mCommands: VescIf.commands()
        mMcConf: VescIf.mcConfig()
        mCustomConf: VescIf.customConfig(0)
        mUtility: Utility
    }
}
